/* auto generated */
vlc_declare_plugin(access_avio);
vlc_declare_plugin(access_demux_avformat);
vlc_declare_plugin(access_http);
vlc_declare_plugin(access_mms);
vlc_declare_plugin(amem);
vlc_declare_plugin(android_surface);
vlc_declare_plugin(audiotrack_android);
vlc_declare_plugin(avcodec);
vlc_declare_plugin(avformat);
vlc_declare_plugin(bandlimited_resampler);
vlc_declare_plugin(blend);
vlc_declare_plugin(converter_fixed);
vlc_declare_plugin(dummy);
vlc_declare_plugin(filesystem);
vlc_declare_plugin(fixed32_mixer);
vlc_declare_plugin(float32_mixer);
vlc_declare_plugin(freetype);
vlc_declare_plugin(libasf);
vlc_declare_plugin(libass);
vlc_declare_plugin(libavi);
vlc_declare_plugin(libmp4);
vlc_declare_plugin(live555);
vlc_declare_plugin(mkv);
vlc_declare_plugin(mpeg_audio);
vlc_declare_plugin(mpgv);
vlc_declare_plugin(packetizer_copy);
vlc_declare_plugin(packetizer_dirac);
vlc_declare_plugin(packetizer_flac);
vlc_declare_plugin(packetizer_h264);
vlc_declare_plugin(packetizer_mlp);
vlc_declare_plugin(packetizer_mpeg4audio);
vlc_declare_plugin(packetizer_mpeg4video);
vlc_declare_plugin(packetizer_mpegvideo);
vlc_declare_plugin(packetizer_vc1);
vlc_declare_plugin(realrtsp);
vlc_declare_plugin(simple_channel_mixer);
vlc_declare_plugin(stream_filter_httplive);
vlc_declare_plugin(stream_filter_record);
vlc_declare_plugin(subsdec);
vlc_declare_plugin(subsusf);
vlc_declare_plugin(subtitle);
vlc_declare_plugin(swscale);
vlc_declare_plugin(trivial_mixer);
vlc_declare_plugin(ts);
vlc_declare_plugin(ugly_resampler);
vlc_declare_plugin(vmem);
vlc_declare_plugin(yuv2rgb);
const void *vlc_builtins_modules[] = {
	vlc_plugin(access_avio),
	vlc_plugin(access_demux_avformat),
	vlc_plugin(access_http),
	vlc_plugin(access_mms),
	vlc_plugin(amem),
	vlc_plugin(android_surface),
	vlc_plugin(audiotrack_android),
	vlc_plugin(avcodec),
	vlc_plugin(avformat),
	vlc_plugin(bandlimited_resampler),
	vlc_plugin(blend),
	vlc_plugin(converter_fixed),
	vlc_plugin(dummy),
	vlc_plugin(filesystem),
	vlc_plugin(fixed32_mixer),
	vlc_plugin(float32_mixer),
	vlc_plugin(freetype),
	vlc_plugin(libasf),
	vlc_plugin(libass),
	vlc_plugin(libavi),
	vlc_plugin(libmp4),
	vlc_plugin(live555),
	vlc_plugin(mkv),
	vlc_plugin(mpeg_audio),
	vlc_plugin(mpgv),
	vlc_plugin(packetizer_copy),
	vlc_plugin(packetizer_dirac),
	vlc_plugin(packetizer_flac),
	vlc_plugin(packetizer_h264),
	vlc_plugin(packetizer_mlp),
	vlc_plugin(packetizer_mpeg4audio),
	vlc_plugin(packetizer_mpeg4video),
	vlc_plugin(packetizer_mpegvideo),
	vlc_plugin(packetizer_vc1),
	vlc_plugin(realrtsp),
	vlc_plugin(simple_channel_mixer),
	vlc_plugin(stream_filter_httplive),
	vlc_plugin(stream_filter_record),
	vlc_plugin(subsdec),
	vlc_plugin(subsusf),
	vlc_plugin(subtitle),
	vlc_plugin(swscale),
	vlc_plugin(trivial_mixer),
	vlc_plugin(ts),
	vlc_plugin(ugly_resampler),
	vlc_plugin(vmem),
	vlc_plugin(yuv2rgb),
	NULL
};
/* auto generated */
